[package]
name = "bilibili-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
color-eyre = "0.6.5"
crossterm = "0.29.0"
qrcode = { version = "0.14.1", default-features = false }
ratatui = { version = "0.30.0", features = ["serde"] }
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
tokio = { version = "1.0", features = ["full"] }
tui-big-text = "0.8.1"
tui-qrcode = { version = "0.2.2", default-features = false }
